# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJ4O18CWLe06giq_I4_pqSIRp7oV-blo

fastapi
uvicorn
scikit-learn
joblib
numpy
pandas
"""